server:
  port: 8000
# 注册中心
eureka:
  client:
    service-url:
      defaultZone: http://rubbish:admin@127.0.0.1:9000/eureka
  instance:
    prefer-ip-address: true
    instance-id: user-a
spring:
  # 数据源
  datasource:
    platform: mysql
    driver-class-name: net.sf.log4jdbc.DriverSpy
    url: jdbc:log4jdbc:mysql://localcent:3306/rubbish_dev?characterEncoding=utf-8
    username: root
    password: 123123
  application:
    name: user
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    database: mysql
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL57Dialect

# 日志
logging:
  level:
    jdbc:
      sqltiming: info
      sqlonly: off
      audit: off
      resultset: off
      connection: off